export { default as CtaSection } from './CtaSection'
export { default as FAQ } from './FAQ'
export { default as Footer } from './Footer'
export { default as Hero } from './Hero'
export { default as Header } from './Header'
export { default as OurProducts } from './OurProducts'
export { default as WhyChoose } from './WhyChoose'
export { default as OurTestimonials } from './OurTestimonials'
